input: /scratch/jam1657/rebase/downloaded/All_Type_II_restriction_enzyme_genes_Protein.fasta
output: /scratch/jam1657/rebase/generated/All_Type_II_restriction_enzyme_genes_Protein.parquet
fasta: /scratch/jam1657/rebase/generated/mmseq_input.faa
cluster: /scratch/jam1657/rebase/generated/cluster.parquet
train: /scratch/jam1657/rebase/generated/train-labeled
val: /scratch/jam1657/rebase/generated/val-labeled
test: /scratch/jam1657/rebase/generated/test-labeled

finput: /scratch/jam1657/rebase/downloaded/All_Type_II_restriction_enzyme_genes_Protein.fasta
final: /scratch/jam1657/rebase/generated/final.csv
temp: /scratch/jam1657/rebase/generated/clusters.tsv
checkpoints: /scratch/jam1657/rebase/models
wandb_dir: /scratch/jam1657/rebase/wandb