input: /scratch/og2114/rebase/data/All_Type_II_restriction_enzyme_genes_Protein.fasta

output: /scratch/og2114/rebase/data/example.csv
fasta: /scratch/og2114/rebase/data/mmseq_input.faa
cluster: /scratch/og2114/rebase/data/cluster-fake.pcsv
train: /scratch/og2114/rebase/data/train-labeled
val: /scratch/og2114/rebase/data/val-labeled
test: /scratch/og2114/rebase/data/test-labeled

finput:  /scratch/og2114/rebase/data/All_Type_II_restriction_enzyme_genes_Protein.fasta
final: /scratch/og2114/rebase/data/final.csv
temp: /scratch/og2114/rebase/data/clusters.tsv
checkpoints: /scratch/og2114/rebase/models
wandb_dir: /scratch/og2114/rebase/logs
# cluster_data: /Users/orangoodman/dev/deeplearning/focus/data/data.parquet