# d_ff: 128
# d_model: 768
d_ff: 64
d_kv: 64
d_model: 2560
batch_size: 16
lr: 1e-2
layers: 4
lr_patience: 100
scheduler: True
gpu: -1
max_epochs: -1
name: small
precision: 16
seq_identity: .3
name: esm2_t36_3B_UR50D
#size -> 1.6 million params
#480 iters on RTX8000 at fp32
