# d_ff: 128
# d_model: 768
d_ff: 512
d_kv: 128
d_model: 512
batch_size: 64
lr: 1e-3
layers: 6
lr_patience: 100
scheduler: True
gpu: -1
max_epochs: -1
precision: 32
seq_identity: .3
lrpower: 2
dna_clust: False
sample_by_cluster: True
name: foldhuge
#size -> 1.6 million params
#480 iters on RTX8000 at fp32
