# d_ff: 128
# d_model: 768
d_ff: 128
d_kv: 128
d_model: 640
batch_size: 128
lr: 1e-2
layers: 4
lr_patience: 100
scheduler: True
gpu: -1
max_epochs: -1
precision: 32
sample_by_cluster: True
seq_identity: .3
name: esm2_t30_150M_UR50D
#size -> 1.6 million params
#480 iters on RTX8000 at fp32

